App\Entity\Book:
    properties:
        isbn:
            - NotBlank: ~
            - Isbn: ~
        title:
            - NotBlank: ~
#        abstract:
#            - Length:
#                min: 0
#                max: 255
#        description:
#            - Length:
#                 min: 0
#                 max: 255
#        author:
#            - Length:
#                min: 0
#                max: 255
        publicationDate:
            -   Date: ~
