resources:
    App\Entity\Greeting: ~
    App\Entity\Book:
        properties:
            reviews:
                subresource:
                    resourceClass: ‘App\Entity\Review’
                    maxDepth: 1
                    collection: true
    App\Entity\Author:
        attributes:
            order:
                lastname: DESC
                firstname: ASC
        properties:
            books:
                subresource:
                    resourceClass: ‘App\Entity\Book’
                    maxDepth: 1
                    collection: true
    App\Entity\Review: ~
