resources:
    App\Entity\Greeting: ~
    App\Entity\Book:
        itemOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['book_read', 'book_write']
            put:
                method: 'PUT'
            delete:
                method: 'DELETE'
        attributes:
            normalization_context:
                groups: ['book_read']
            denormalization_context:
                groups: ['book_write']
            filters: ['book.search_filter']
        properties:
            reviews:
                subresource:
                    resourceClass: ‘App\Entity\Review’
                    maxDepth: 1
                    collection: true
    App\Entity\Author:
        itemOperations:
            get:
                method: 'GET'
                normalization_context:
                    groups: ['author_read', 'author_write']
                put:
                    method: 'PUT'
                delete:
                    method: 'DELETE'
        attributes:
            normalization_context:
                groups: ['author_read']
            denormalization_context:
                groups: ['author_write']
            order:
                lastname: DESC
                firstname: ASC
        properties:
            books:
                subresource:
                    resourceClass: ‘App\Entity\Book’
                    maxDepth: 1
                    collection: true
    App\Entity\Review: ~
